/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.awt.*;

/**
 * App class
 */
public class App {
    /** Game window instance */
    private EinsteinWindow einsteinWindow;
    /** Menu window instance */
    private MenuWindow menuWindow;

    /**
     * Constructor
     */
    public App() {
        try {
            this.menuWindow = new MenuWindow();
//            this.einsteinWindow = new EinsteinWindow();
        } catch (HeadlessException e) {
            e.printStackTrace();
        }
    }

    /**
     * Shows the window
     */
    public void showWindow() {
        this.menuWindow.setVisible(true);
    }

    /**
     * main function
     *
     * @param args command line arguments
     */
    public static void main(String[] args) {
        App app = new App();
        app.showWindow();
    }
}
